#!/usr/bin/env perl
use strict;
use warnings;

# Autogenerate user-mode syscall wrappers, similar to xv6's usys.pl.
# Extend \@syscalls when new entries are added to kernel/syscall.h.
my @syscalls = qw(
    getpid
    exit
    wait
    fork
    yield
    sbrk
    write
    read
    kill
    open
    close
    sleep
);

print <<"HEADER";
# Autogenerated by user/usys.pl -- DO NOT EDIT.
#include "../kernel/syscall.h"

HEADER

foreach my $name (@syscalls) {
    print ".globl $name\n";
    print "$name:\n";
    print "\tli a7, SYS_$name\n";
    print "\tecall\n";
    print "\tret\n\n";
}
